rate: 0.1

# ROS1 
ROS_IP: 127.0.0.1
ROS_MASTER_URI: http://127.0.0.1:11311
#ROS2
ROS_DOMAIN_ID: 1
ROS_LOCALHOST_ONLY: 0

#topic
ros1_to_ros2:
  - ros1_name: /chatter
    ros1_type: std_msgs/String
    ros2_name: /chatter_ros2
    ros2_type: std_msgs/msg/String
  - ros1_name: /points_map
    ros1_type: sensor_msgs/PointCloud2
    ros2_name: /points_map_ros2
    ros2_type: sensor_msgs/msg/PointCloud2
ros2_to_ros1:
  - ros1_name: /chatter
    ros1_type: std_msgs/String
    ros2_name: /chatter_ros2
    ros2_type: std_msgs/msg/String
  - ros1_name: /points_map
    ros1_type: sensor_msgs/PointCloud2
    ros2_name: /points_map_ros2
    ros2_type: sensor_msgs/msg/PointCloud2